title: QUD — Demo Test Docs
description: Правила, процедуры и FAQ

# Подключаем тему как удалённую (надёжно для project pages)
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# ВАЖНО: для project pages baseurl = "/<имя_репозитория>"
url: "https://qudinfo.github.io"
baseurl: "/QUD_test_rules"

search_enabled: true
nav_sort: case_insensitive

aux_links:
  WebTrader:
    - "https://www.mql5.com/en/trading"
  Support (email):
    - "mailto:gatequd@proton.me"

footer_content: ""        # отключает надпись Just the Docs
last_edit_timestamp: false
last_edit_time_format: "%Y-%m-%d %H:%M %z"
